// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActionInfo = "action_info"

// ActionInfo mapped from table <action_info>
type ActionInfo struct {
	ID                string  `gorm:"column:id;primaryKey" json:"id"`                                                      // ID
	SceneAutomationID string  `gorm:"column:scene_automation_id;not null" json:"scene_automation_id"` // Scene linkage ID (foreign key - cascade delete)
	ActionTarget      *string `gorm:"column:action_target; left empty if it's a single class device)" json:"action_target"`  // Target ID for action (device ID, scene ID, alarm ID; left empty if it's a single class device)
	ActionType        string  `gorm:"column:action_type;not null" json:"action_type"` // Action type: 10: single device, 11: single class device, 20: activate scene, 30: trigger alarm, 40: service
	ActionParamType   *string `gorm:"column:action_param_type" json:"action_param_type"` // Telemetry TEL attribute ATTR command CMD
	ActionParam       *string `gorm:"column:action_param; valid for action types 10 and 11 - Identifier" json:"action_param"` // Action parameter; valid for action types 10 and 11 - Identifier
	ActionValue       *string `gorm:"column:action_value" json:"action_value"` // Target value
	Remark            *string `gorm:"column:remark" json:"remark"` // Remark
}

// TableName ActionInfo's table name
func (*ActionInfo) TableName() string {
	return TableNameActionInfo
}
