// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlarmConfig = "alarm_config"

// AlarmConfig mapped from table <alarm_config>
type AlarmConfig struct {
	ID                  string    `gorm:"column:id;primaryKey" json:"id"`                                                      // ID
	Name                string    `gorm:"column:name;not null" json:"name"`                                    // Alarm name
	Description         *string   `gorm:"column:description" json:"description"`                       // Alarm description
	AlarmLevel          string    `gorm:"column:alarm_level;not null" json:"alarm_level"` // Alarm level: H: High, M: Medium, L: Low
	NotificationGroupID string    `gorm:"column:notification_group_id;not null" json:"notification_group_id"` // Notification group ID
	CreatedAt           time.Time `gorm:"column:created_at;not null" json:"created_at"`                                           // Creation time
	UpdatedAt           time.Time `gorm:"column:updated_at;not null" json:"updated_at"`                                           // Last update time
	TenantID            string    `gorm:"column:tenant_id;not null" json:"tenant_id"`                                             // Tenant ID
	Remark              *string   `gorm:"column:remark" json:"remark"`                                                           // Remark
	Enabled             string    `gorm:"column:enabled;not null" json:"enabled"`               // Enabled (Y: Yes, N: No)
}

// TableName AlarmConfig's table name
func (*AlarmConfig) TableName() string {
	return TableNameAlarmConfig
}
