// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlarmInfo = "alarm_info"

// AlarmInfo mapped from table <alarm_info>
type AlarmInfo struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`                                              // ID
	AlarmConfigID    string    `gorm:"column:alarm_config_id;not null" json:"alarm_config_id"` // Alarm configuration ID
	Name             string    `gorm:"column:name;not null" json:"name"`                             // Alarm name
	AlarmTime        time.Time `gorm:"column:alarm_time;not null" json:"alarm_time"`                 // Alarm time
	Description      *string   `gorm:"column:description" json:"description"`                // Alarm description
	Content          *string   `gorm:"column:content" json:"content"`                                  // Content (details of the alarm)
	Processor        *string   `gorm:"column:processor" json:"processor"`                         // Processor ID (person who handles the alarm)
	ProcessingResult string    `gorm:"column:processing_result;not null" json:"processing_result"` // Processing result
	TenantID         string    `gorm:"column:tenant_id;not null" json:"tenant_id"`                   // Tenant ID
	Remark           *string   `gorm:"column:remark" json:"remark"`                                                   // Remark (optional)
	AlarmLevel       *string   `gorm:"column:alarm_level" json:"alarm_level"` // Alarm level (L: Low, M: Medium, H: High)
}

// TableName AlarmInfo's table name
func (*AlarmInfo) TableName() string {
	return TableNameAlarmInfo
}
