// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlarmHistory = "alarm_history"

// AlarmHistory mapped from table <alarm_history>
type AlarmHistory struct {
	ID                string    `gorm:"column:id;primaryKey" json:"id"`                                              // ID
	AlarmConfigID     string    `gorm:"column:alarm_config_id;not null" json:"alarm_config_id"`                       // Alarm configuration ID
	GroupID           string    `gorm:"column:group_id;not null" json:"group_id"`                                     // Group ID
	SceneAutomationID string    `gorm:"column:scene_automation_id;not null" json:"scene_automation_id"`               // Scene automation ID
	Name              string    `gorm:"column:name;not null" json:"name"`                           // Alarm name
	Description       *string   `gorm:"column:description" json:"description"`              // Alarm description
	Content           *string   `gorm:"column:content" json:"content"`            // Content (cause of the alarm)
	AlarmStatus       string    `gorm:"column:alarm_status;not null" json:"alarm_status"` // Alarm status: L: Low, M: Medium, H: High, N: Normal
	TenantID          string    `gorm:"column:tenant_id;not null" json:"tenant_id"`                 // Tenant ID
	Remark            *string   `gorm:"column:remark" json:"remark"`                                                  // Remark
	CreateAt          time.Time `gorm:"column:create_at;not null" json:"create_at"`             // Creation time
	AlarmDeviceList   string    `gorm:"column:alarm_device_list;not null" json:"alarm_device_list"` // Triggered device ID list
}

// TableName AlarmHistory's table name
func (*AlarmHistory) TableName() string {
	return TableNameAlarmHistory
}
