// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAttributeData = "attribute_datas"

// AttributeData mapped from table <attribute_datas>
type AttributeData struct {
	ID       string    `gorm:"column:id;not null" json:"id"`                                            // ID
	DeviceID string    `gorm:"column:device_id;not null" json:"device_id"` // Device ID (foreign key - cascade delete)
	Key      string    `gorm:"column:key;not null" json:"key"`                    // Data identifier
	T        time.Time `gorm:"column:ts;not null" json:"ts"`                          // Report time
	BoolV    *bool     `gorm:"column:bool_v" json:"bool_v"`                                              // Boolean value
	NumberV  *float64  `gorm:"column:number_v" json:"number_v"`                                          // Numeric value
	StringV  *string   `gorm:"column:string_v" json:"string_v"`                                          // String value
	TenantID *string   `gorm:"column:tenant_id" json:"tenant_id"`                                        // Tenant ID (optional)
}

// TableName AttributeData's table name
func (*AttributeData) TableName() string {
	return TableNameAttributeData
}
