// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAttributeSetLog = "attribute_set_logs"

// AttributeSetLog mapped from table <attribute_set_logs>
type AttributeSetLog struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`                                          // ID
	DeviceID      string    `gorm:"column:device_id;not null" json:"device_id"` // Device ID (foreign key - cascade delete)
	OperationType *string   `gorm:"column:operation_type" json:"operation_type"` // Operation type 1-Manual operation 2-Automatic trigger
	MessageID     *string   `gorm:"column:message_id" json:"message_id"`                    // Message ID
	Datum         *string   `gorm:"column:data" json:"data"`                              // Sent content
	RspDatum      *string   `gorm:"column:rsp_data" json:"rsp_data"`                  // Response content
	Status        *string   `gorm:"column:status" json:"status"`                   // 1-Success 2-Failure
	ErrorMessage  *string   `gorm:"column:error_message" json:"error_message"`           // Error message
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`        // Creation time
	UserID        *string   `gorm:"column:user_id" json:"user_id"`                       // Operator user
	Description   *string   `gorm:"column:description" json:"description"`                 // Description
}

// TableName AttributeSetLog's table name
func (*AttributeSetLog) TableName() string {
	return TableNameAttributeSetLog
}
