// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBoard = "boards"

// Board mapped from table <boards>
type Board struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`                      // Id
	Name        string    `gorm:"column:name;not null" json:"name"`             // Board Name
	Config      *string   `gorm:"column:config;default:{}" json:"config"` // Board Configuration
	TenantID    string    `gorm:"column:tenant_id;not null" json:"tenant_id"` // Tenant ID (Unique)
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`                     // Created Time
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`                     // Updated Time
	HomeFlag    string    `gorm:"column:home_flag;not null" json:"home_flag"` // Homepage Flag, default 'N', 'Y' means it is the homepage
	Description *string   `gorm:"column:description" json:"description"`        // Description
	Remark      *string   `gorm:"column:remark" json:"remark"`                       // Remark
	MenuFlag    *string   `gorm:"column:menu_flag" json:"menu_flag"` // Menu Flag, default 'N', 'Y' indicates it appears in the menu
}

// TableName Board's table name
func (*Board) TableName() string {
	return TableNameBoard
}
