// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommandSetLog = "command_set_logs"

// CommandSetLog mapped from table <command_set_logs>
type CommandSetLog struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	DeviceID      string    `gorm:"column:device_id;not null" json:"device_id"`      // Device ID (foreign key - associated deletion)
	OperationType *string   `gorm:"column:operation_type" json:"operation_type"` // Operation type: 1 - Manual operation, 2 - Automatically triggered
	MessageID     *string   `gorm:"column:message_id" json:"message_id"`                      // Message ID
	Datum         *string   `gorm:"column:data" json:"data"`                                  // Sent content
	RspDatum      *string   `gorm:"column:rsp_data" json:"rsp_data"`                          // Returned content
	Status        *string   `gorm:"column:status" json:"status"`                       // 1 - Sent successfully, 2 - Failure
	ErrorMessage  *string   `gorm:"column:error_message" json:"error_message"`                // Error message
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`             // Creation time
	UserID        *string   `gorm:"column:user_id" json:"user_id"`                            // Operation user
	Description   *string   `gorm:"column:description" json:"description"`                      // Description
	Identify      *string   `gorm:"column:identify" json:"identify"`                         // Data identifier
}

// TableName CommandSetLog's table name
func (*CommandSetLog) TableName() string {
	return TableNameCommandSetLog
}
