// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataPolicy = "data_policy"

// DataPolicy mapped from table <data_policy>
type DataPolicy struct {
	ID                  string     `gorm:"column:id;primaryKey" json:"id"`                                                   // ID
	DataType            string     `gorm:"column:data_type;not null" json:"data_type"`   // Cleanup type: 1-Device data, 2-Operation log
	RetentionDay        int32      `gorm:"column:retention_days;not null" json:"retention_days"`          // Data retention period (days)
	LastCleanupTime     *time.Time `gorm:"column:last_cleanup_time" json:"last_cleanup_time"`                       // Last cleanup time
	LastCleanupDataTime *time.Time `gorm:"column:last_cleanup_data_time" json:"last_cleanup_data_time"` // Last data cleanup timestamp (actual cleanup time)
	Enabled             string     `gorm:"column:enabled;not null" json:"enabled"`             // Enabled status: 1-Enabled, 2-Disabled
	Remark              *string    `gorm:"column:remark" json:"remark"`                                                    // Remark
}

// TableName DataPolicy's table name
func (*DataPolicy) TableName() string {
	return TableNameDataPolicy
}
