// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataScript = "data_scripts"

// DataScript mapped from table <data_scripts>
type DataScript struct {
	ID              string     `gorm:"column:id;primaryKey" json:"id"`                                                        // ID
	Name            string     `gorm:"column:name;not null" json:"name"`                                                      // Name
	DeviceConfigID  string     `gorm:"column:device_config_id;not null" json:"device_config_id"` // Device config ID (cascading delete)
	EnableFlag      string     `gorm:"column:enable_flag;not null" json:"enable_flag"` // Enable flag Y - Enabled, N - Disabled (default enabled)
	Content         *string    `gorm:"column:content" json:"content"`                                                     // Content
	ScriptType      string     `gorm:"column:script_type;not null" json:"script_type"` // Script type: A - Telemetry report preprocessing, B - Telemetry downlink preprocessing, C - Attribute report preprocessing, D - Attribute downlink preprocessing
	LastAnalogInput *string    `gorm:"column:last_analog_input" json:"last_analog_input"`                      // Last analog input
	Description     *string    `gorm:"column:description" json:"description"`                                         // Description
	CreatedAt       *time.Time `gorm:"column:created_at" json:"created_at"`                                         // Creation time
	UpdatedAt       *time.Time `gorm:"column:updated_at" json:"updated_at"`                                           // Update time
	Remark          *string    `gorm:"column:remark" json:"remark"`                                                       // Remark
}

// TableName DataScript's table name
func (*DataScript) TableName() string {
	return TableNameDataScript
}
