// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceTemplate = "device_templates"

// DeviceTemplate mapped from table <device_templates>
type DeviceTemplate struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`        // Id
	Name           string    `gorm:"column:name;not null" json:"name"`    // Template Name
	Author         *string   `gorm:"column:author" json:"author"`           // Author
	Version        *string   `gorm:"column:version" json:"version"`        // Version Number
	Description    *string   `gorm:"column:description" json:"description"` // Description
	TenantID       string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Flag           *int16    `gorm:"column:flag;default:1" json:"flag"`                // Flag, default 1
	Label          *string   `gorm:"column:label" json:"label"`                            // Label
	WebChartConfig *string   `gorm:"column:web_chart_config" json:"web_chart_config"` // Web Chart Configuration
	AppChartConfig *string   `gorm:"column:app_chart_config" json:"app_chart_config"` // App Chart Configuration
	Remark         *string   `gorm:"column:remark" json:"remark"`                          // Remark
	Path           *string   `gorm:"column:path" json:"path"`                            // Image Path
}

// TableName DeviceTemplate's table name
func (*DeviceTemplate) TableName() string {
	return TableNameDeviceTemplate
}
