// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDeviceModelCustomCommand = "device_model_custom_commands"

// DeviceModelCustomCommand mapped from table <device_model_custom_commands>
// DeviceModelCustomCommand mapped from table <device_model_custom_commands>
type DeviceModelCustomCommand struct {
	ID               string  `gorm:"column:id;primaryKey" json:"id"`                                          // ID
	DeviceTemplateID string  `gorm:"column:device_template_id;not null" json:"device_template_id"` // Device template ID
	ButtomName       string  `gorm:"column:buttom_name;not null" json:"buttom_name"`                     // Button name
	DataIdentifier   string  `gorm:"column:data_identifier;not null" json:"data_identifier"`         // Data identifier
	Description      *string `gorm:"column:description" json:"description"`                             // Description
	Instruct         *string `gorm:"column:instruct" json:"instruct"`                          // Instruction content
	EnableStatus     string  `gorm:"column:enable_status;not null" json:"enable_status"` // Enable status: enable-enable, disable-disable
	Remark           *string `gorm:"column:remark" json:"remark"`                                           // Remarks
	TenantID         string  `gorm:"column:tenant_id;not null" json:"tenant_id"`                                           // Tenant ID
}

// TableName DeviceModelCustomCommand's table name
func (*DeviceModelCustomCommand) TableName() string {
	return TableNameDeviceModelCustomCommand
}
