// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceModelTelemetry = "device_model_telemetry"

// DeviceModelTelemetry mapped from table <device_model_telemetry>
type DeviceModelTelemetry struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`                                   // ID
	DeviceTemplateID string    `gorm:"column:device_template_id;not null" json:"device_template_id"` // Device template ID
	DataName         *string   `gorm:"column:data_name" json:"data_name"`                             // Data name
	DataIdentifier   string    `gorm:"column:data_identifier;not null" json:"data_identifier"`  // Data identifier
	ReadWriteFlag    *string   `gorm:"column:read_write_flag" json:"read_write_flag"` // Read/Write flag R-Read W-Write RW-ReadWrite
	DataType         *string   `gorm:"column:data_type" json:"data_type"`         // Data type String Number Boolean
	Unit             *string   `gorm:"column:unit" json:"unit"`                                          // Unit
	Description      *string   `gorm:"column:description" json:"description"`                     // Description
	AdditionalInfo   *string   `gorm:"column:additional_info" json:"additional_info"`         // Additional info
	CreatedAt        time.Time `gorm:"column:created_at;not null" json:"created_at"`            // Creation time
	UpdatedAt        time.Time `gorm:"column:updated_at;not null" json:"updated_at"`              // Update time
	Remark           *string   `gorm:"column:remark" json:"remark"`                                    // Remark
	TenantID         string    `gorm:"column:tenant_id;not null" json:"tenant_id"`                                   // Tenant ID
}

// TableName DeviceModelTelemetry's table name
func (*DeviceModelTelemetry) TableName() string {
	return TableNameDeviceModelTelemetry
}
