// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceConfig = "device_configs"

// DeviceConfig mapped from table <device_configs>
type DeviceConfig struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`                                           // ID
	Name             string    `gorm:"column:name;not null" json:"name"`                                         // Name
	DeviceTemplateID *string   `gorm:"column:device_template_id" json:"device_template_id"`        // Device template ID
	DeviceType       string    `gorm:"column:device_type;not null" json:"device_type"` // Device type: 1 - Direct device, 2 - Gateway device, 3 - Gateway sub-device
	ProtocolType     *string   `gorm:"column:protocol_type" json:"protocol_type"`                       // Protocol type
	VoucherType      *string   `gorm:"column:voucher_type" json:"voucher_type"`                         // Voucher type
	ProtocolConfig   *string   `gorm:"column:protocol_config" json:"protocol_config"`    // Protocol form configuration
	DeviceConnType   *string   `gorm:"column:device_conn_type" json:"device_conn_type"` // Device connection type (default A) A - Device connects to platform, B - Platform connects to device
	AdditionalInfo   *string   `gorm:"column:additional_info;default:{}" json:"additional_info"` // Additional information
	Description      *string   `gorm:"column:description" json:"description"`                             // Description
	TenantID         string    `gorm:"column:tenant_id;not null" json:"tenant_id"`                         // Tenant ID
	CreatedAt        time.Time `gorm:"column:created_at;not null" json:"created_at"`                   // Creation time
	UpdatedAt        time.Time `gorm:"column:updated_at;not null" json:"updated_at"`                     // Update time
	Remark           *string   `gorm:"column:remark" json:"remark"`                                            // Remark
	OtherConfig      *string   `gorm:"column:other_config" json:"other_config"`                  // Other configuration
}

// TableName DeviceConfig's table name
func (*DeviceConfig) TableName() string {
	return TableNameDeviceConfig
}
