// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceModelCustomControl = "device_model_custom_control"

// DeviceModelCustomControl mapped from table <device_model_custom_controls>
type DeviceModelCustomControl struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`                                                    // ID
	DeviceTemplateID string    `gorm:"column:device_template_id;not null" json:"device_template_id"`        // Device template ID
	Name             string    `gorm:"column:name;not null" json:"name"`                                                 // Name
	ControlType      string    `gorm:"column:control_type;not null" json:"control_type"` // Control type: 1. Control type, 2. telemetry - telemetry, 3. attributes - attributes
	Description      *string   `gorm:"column:description" json:"description"`                                      // Description
	Content          *string   `gorm:"column:content" json:"content"`                                      // Instruction content
	EnableStatus     string    `gorm:"column:enable_status;not null" json:"enable_status"` // Enable status: enable - enabled, disable - disabled
	CreatedAt        time.Time `gorm:"column:created_at;not null" json:"created_at"`                              // Creation time
	UpdatedAt        time.Time `gorm:"column:updated_at;not null" json:"updated_at"`                               // Update time
	Remark           *string   `gorm:"column:remark" json:"remark"`                                                   // Remarks
	TenantID         string    `gorm:"column:tenant_id;not null" json:"tenant_id"`                                                   // Tenant ID
}

// TableName DeviceModelCustomControl's table name
func (*DeviceModelCustomControl) TableName() string {
	return TableNameDeviceModelCustomControl
}
