// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventData = "event_datas"

// EventData mapped from table <event_datas>
type EventData struct {
	ID       string    `gorm:"column:id;primaryKey" json:"id"`              // ID
	DeviceID string    `gorm:"column:device_id;not null" json:"device_id"` // Device ID (foreign key - cascade delete)
	Identify string    `gorm:"column:identify;not null" json:"identify"`           // Data identifier
	T        time.Time `gorm:"column:ts;not null" json:"ts"`                        // Reported time
	Datum    *string   `gorm:"column:data" json:"data"`                               // Data
	TenantID *string   `gorm:"column:tenant_id" json:"tenant_id"`                                     // Tenant ID
}

// TableName EventData's table name
func (*EventData) TableName() string {
	return TableNameEventData
}
