// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameExpectedData = "expected_datas"

// ExpectedData mapped from table <expected_datas>
type ExpectedData struct {
	ID         string     `gorm:"column:id;primaryKey" json:"id"`                          // Unique identifier for the command (UUID)
	DeviceID   string     `gorm:"column:device_id;not null" json:"device_id"`                                      // Target device ID
	SendType   string     `gorm:"column:send_type;not null" json:"send_type"`   // Command type (e.g., telemetry, attribute, command)
	Payload    string     `gorm:"column:payload;not null" json:"payload"`             // Command content (specific command parameters)
	CreatedAt  time.Time  `gorm:"column:created_at;not null" json:"created_at"`                            // Command generation time
	SendTime   *time.Time `gorm:"column:send_time" json:"send_time"`                             // Actual command send time (if sent)
	Status     string     `gorm:"column:status;not null;default:pending" json:"status"` // Command status (pending, sent, expired), default pending
	Message    *string    `gorm:"column:message" json:"message"`       // Status additional information (e.g., reason for send failure)
	ExpiryTime *time.Time `gorm:"column:expiry_time" json:"expiry_time"`                           // Command expiry time (optional)
	Label      *string    `gorm:"column:label" json:"label"`                                              // Command label (optional)
	TenantID   string     `gorm:"column:tenant_id;not null" json:"tenant_id"`                 // Tenant ID (for multi-tenant systems)
}

// TableName ExpectedData's table name
func (*ExpectedData) TableName() string {
	return TableNameExpectedData
}
