// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGroup = "groups"

// Group mapped from table <groups>
type Group struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	ParentID    *string   `gorm:"column:parent_id;default:0" json:"parent_id"` // Default 0 indicates parent group
	Tier        int32     `gorm:"column:tier;not null;default:1" json:"tier"`  // Level, starting from 1
	Name        string    `gorm:"column:name;not null" json:"name"`               // Group name
	Description *string   `gorm:"column:description" json:"description"`        // Description
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`   // Creation time
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`   // Update time
	Remark      *string   `gorm:"column:remark" json:"remark"`
	TenantID    string    `gorm:"column:tenant_id;not null" json:"tenant_id"` // Tenant ID
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
