// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLogo = "logo"

// Logo mapped from table <logo>
type Logo struct {
	ID             string  `gorm:"column:id;primaryKey" json:"id"`                               // Id
	SystemName     string  `gorm:"column:system_name;not null" json:"system_name"`       // System name
	LogoCache      string  `gorm:"column:logo_cache;not null" json:"logo_cache"`           // Site logo
	LogoBackground string  `gorm:"column:logo_background;not null" json:"logo_background"` // Page load logo
	LogoLoading    string  `gorm:"column:logo_loading;not null" json:"logo_loading"` // Loading page logo
	HomeBackground string  `gorm:"column:home_background;not null" json:"home_background"` // Home page background
	Remark         *string `gorm:"column:remark" json:"remark"`
}

// TableName Logo's table name
func (*Logo) TableName() string {
	return TableNameLogo
}
