// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessagePushManage = "message_push_manage"

// MessagePushManage mapped from table <message_push_manage>
type MessagePushManage struct {
	ID           string     `gorm:"column:id;primaryKey" json:"id"`
	UserID       string     `gorm:"column:user_id;not null" json:"user_id"`               // User ID
	PushID       string     `gorm:"column:push_id;not null" json:"push_id"`               // Push ID
	DeviceType   string     `gorm:"column:device_type;not null" json:"device_type"`   // Device type
	Status       int16      `gorm:"column:status;not null;default:1" json:"status"` // Type 1: Active, 2: Inactive
	CreateTime   time.Time  `gorm:"column:create_time;not null" json:"create_time"` // Creation time
	UpdateTime   *time.Time `gorm:"column:update_time" json:"update_time"`           // Update time
	DeleteTime   *time.Time `gorm:"column:delete_time" json:"delete_time"`         // Deletion time
	LastPushTime *time.Time `gorm:"column:last_push_time" json:"last_push_time"` // Last push time
	ErrCount     *int32     `gorm:"column:err_count;default:1" json:"err_count"` // Error count for push attempts
	InactiveTime *time.Time `gorm:"column:inactive_time" json:"inactive_time"` // Inactive time marker
}

// TableName MessagePushManage's table name
func (*MessagePushManage) TableName() string {
	return TableNameMessagePushManage
}
