// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameMessagePushRuleLog = "message_push_rule_log"

// MessagePushRuleLog mapped from table <message_push_rule_log>
type MessagePushRuleLog struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`
	PushID     string    `gorm:"column:push_id;not null" json:"push_id"`
	Type       int16     `gorm:"column:type;not null" json:"type"` // 1: Active invalidation, 2: Passive invalidation, 3: Scheduled task, 4: Auto cleanup
	CreateTime time.Time `gorm:"column:create_time;not null" json:"create_time"`  // Creation time
}

// TableName MessagePushRuleLog's table name
func (*MessagePushRuleLog) TableName() string {
	return TableNameMessagePushRuleLog
}
