// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessagePushConfig = "message_push_config"

// MessagePushConfig mapped from table <message_push_config>
type MessagePushConfig struct {
	ID         string     `gorm:"column:id;primaryKey" json:"id"`
	URL        string     `gorm:"column:url;not null" json:"url"`                                 // Push URL
	ConfigType int16      `gorm:"column:config_type;not null;default:1" json:"config_type"` // Configuration type 1: Push URL
	CreateTime time.Time  `gorm:"column:create_time;not null" json:"create_time"`            // Creation time
	UpdateTime *time.Time `gorm:"column:update_time" json:"update_time"`                       // Update time
}

// TableName MessagePushConfig's table name
func (*MessagePushConfig) TableName() string {
	return TableNameMessagePushConfig
}
