// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessagePushLog = "message_push_log"

// MessagePushLog mapped from table <message_push_log>
type MessagePushLog struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	UserID      string    `gorm:"column:user_id;not null" json:"user_id"`               // User ID
	MessageType int64     `gorm:"column:message_type;not null" json:"message_type"` // Message type 1: Alert message
	Content     string    `gorm:"column:content;not null" json:"content"`       // Message content
	Status      int16     `gorm:"column:status;not null" json:"status"` // 1: Push successful, 2: Push failed
	ErrMessage  string    `gorm:"column:err_message;not null" json:"err_message"` // Error message
	CreateTime  time.Time `gorm:"column:create_time;not null" json:"create_time"`    // Send time
}

// TableName MessagePushLog's table name
func (*MessagePushLog) TableName() string {
	return TableNameMessagePushLog
}
