// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotificationGroup = "notification_groups"

// NotificationGroup mapped from table <notification_groups>
type NotificationGroup struct {
	ID                 string    `gorm:"column:id;primaryKey" json:"id"`
	Name               string    `gorm:"column:name;not null" json:"name"`                                              // Name
	NotificationType   string    `gorm:"column:notification_type;not null" json:"notification_type"` // Notification type: MEMBER-User notification, EMAIL-Email notification, SME-SMS notification, VOICE-Voice notification, WEBHOOK-webhook
	Status             string    `gorm:"column:status;not null" json:"status"`  // Notification status: ON-Enabled, OFF-Disabled
	NotificationConfig *string   `gorm:"column:notification_config" json:"notification_config"`   // Notification configuration
	Description        *string   `gorm:"column:description" json:"description"`                                 // Description
	TenantID           string    `gorm:"column:tenant_id;not null" json:"tenant_id"`                              // Tenant ID
	CreatedAt          time.Time `gorm:"column:created_at;not null" json:"created_at"`                        // Creation time
	UpdatedAt          time.Time `gorm:"column:updated_at;not null" json:"updated_at"`                          // Update time
	Remark             *string   `gorm:"column:remark" json:"remark"`                                                // Remarks
}

// TableName NotificationGroup's table name
func (*NotificationGroup) TableName() string {
	return TableNameNotificationGroup
}
