// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNotificationServicesConfig = "notification_services_config"

// NotificationServicesConfig mapped from table <notification_services_config>
type NotificationServicesConfig struct {
	ID         string  `gorm:"column:id;primaryKey" json:"id"`
	Config     *string `gorm:"column:config" json:"config"`                             // Notification configuration
	NoticeType string  `gorm:"column:notice_type;not null" json:"notice_type"` // Notification type: EMAIL-Email configuration, SME-SMS configuration
	Status     string  `gorm:"column:status;not null" json:"status"`           // Status: OPEN-Enabled, CLOSE-Disabled
	Remark     *string `gorm:"column:remark" json:"remark"`                                                              // Remarks
}

// TableName NotificationServicesConfig's table name
func (*NotificationServicesConfig) TableName() string {
	return TableNameNotificationServicesConfig
}
