// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotificationHistory = "notification_histories"

// NotificationHistory mapped from table <notification_histories>
type NotificationHistory struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	SendTime         time.Time `gorm:"column:send_time;not null" json:"send_time"`                        // Send time
	SendContent      *string   `gorm:"column:send_content" json:"send_content"`                        // Send content
	SendTarget       string    `gorm:"column:send_target;not null" json:"send_target"`                  // Send target
	SendResult       *string   `gorm:"column:send_result" json:"send_result"` // Send result: SUCCESS-Success, FAILURE-Failure
	NotificationType string    `gorm:"column:notification_type;not null" json:"notification_type"` // Notification type: MEMBER-User notification, EMAIL-Email notification, SME-SMS notification, VOICE-Voice notification, WEBHOOK-webhook
	TenantID         string    `gorm:"column:tenant_id;not null" json:"tenant_id"`                       // Tenant ID
	Remark           *string   `gorm:"column:remark" json:"remark"`                                         // Remarks
}

// TableName NotificationHistory's table name
func (*NotificationHistory) TableName() string {
	return TableNameNotificationHistory
}
