// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOneTimeTask = "one_time_tasks"

// OneTimeTask mapped from table <one_time_tasks>
type OneTimeTask struct {
	ID                string    `gorm:"column:id;primaryKey" json:"id"`
	SceneAutomationID string    `gorm:"column:scene_automation_id;not null" json:"scene_automation_id"`          // Scene automation ID (foreign key - cascade delete)
	ExecutionTime     time.Time `gorm:"column:execution_time;not null" json:"execution_time"`                               // Execution time
	ExecutingState    string    `gorm:"column:executing_state;not null" json:"executing_state"` // Execution state: NEX - Not executed, EXE - Executed, EXP - Expired without execution
	Enabled           string    `gorm:"column:enabled;not null" json:"enabled"`                                   // Enabled status: Y - Enabled, N - Disabled
	Remark            *string   `gorm:"column:remark" json:"remark"`
	ExpirationTime    int64     `gorm:"column:expiration_time;not null" json:"expiration_time"` // Expiration time (default greater than execution time by five minutes 5min 10min 30min 1h 1day) in minutes
}

// TableName OneTimeTask's table name
func (*OneTimeTask) TableName() string {
	return TableNameOneTimeTask
}
