// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOperationLog = "operation_logs"

// OperationLog mapped from table <operation_logs>
// OperationLog represents an operation log entity.
type OperationLog struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`                     // ID
	IP              string    `gorm:"column:ip;not null" json:"ip"`                 // Request IP
	Path            *string   `gorm:"column:path" json:"path"`                     // Request URL
	UserID          string    `gorm:"column:user_id;not null" json:"user_id"`  // Operator User ID
	Name            *string   `gorm:"column:name" json:"name"`                        // API Name
	CreatedAt       time.Time `gorm:"column:created_at;not null" json:"created_at"` // Creation Time
	Latency         *int64    `gorm:"column:latency" json:"latency"`               // Latency in milliseconds
	RequestMessage  *string   `gorm:"column:request_message" json:"request_message"` // Request Content
	ResponseMessage *string   `gorm:"column:response_message" json:"response_message"` // Response Content
	TenantID        string    `gorm:"column:tenant_id;not null" json:"tenant_id"`    // Tenant ID
	Remark          *string   `gorm:"column:remark" json:"remark"`                                    // Remarks
}

// TableName OperationLog's table name
func (*OperationLog) TableName() string {
	return TableNameOperationLog
}
