// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOtaUpgradeTask = "ota_upgrade_tasks"

// OtaUpgradeTask mapped from table <ota_upgrade_tasks>
// OtaUpgradeTask represents an OTA (Over-the-Air) upgrade task.
type OtaUpgradeTask struct {
	ID                  string    `gorm:"column:id;primaryKey" json:"id"`                                                   // ID
	Name                string    `gorm:"column:name;not null" json:"name"`                                           // Task Name
	OtaUpgradePackageID string    `gorm:"column:ota_upgrade_package_id;not null" json:"ota_upgrade_package_id"` // OTA Upgrade Package ID (foreign key, cascading delete)
	Description         *string   `gorm:"column:description" json:"description"`                                          // Description
	CreatedAt           time.Time `gorm:"column:created_at;not null" json:"created_at"`                               // Creation Time
	Remark              *string   `gorm:"column:remark" json:"remark"`                                                    // Remarks
}

// TableName OtaUpgradeTask's table name
func (*OtaUpgradeTask) TableName() string {
	return TableNameOtaUpgradeTask
}
