// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOtaUpgradePackage = "ota_upgrade_packages"

// OtaUpgradePackage mapped from table <ota_upgrade_packages>
type OtaUpgradePackage struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                               // ID
	Name           string     `gorm:"column:name;not null" json:"name"`           // Upgrade Package Name
	Version        string     `gorm:"column:version;not null" json:"version"`  // Upgrade Package Version
	TargetVersion  *string    `gorm:"column:target_version" json:"target_version"` // Target Version to Upgrade
	DeviceConfigID string     `gorm:"column:device_config_id;not null" json:"device_config_id"` // Device Configuration ID
	Module         *string    `gorm:"column:module" json:"module"`                         // Module Name
	PackageType    int16      `gorm:"column:package_type;not null" json:"package_type"` // Package Type: 1-Differential 2-Full Package
	SignatureType  *string    `gorm:"column:signature_type" json:"signature_type"` // Signature Algorithm (MD5, SHA256)
	AdditionalInfo *string    `gorm:"column:additional_info;default:{}" json:"additional_info"` // Additional Information
	Description    *string    `gorm:"column:description" json:"description"`              // Description
	PackageURL     *string    `gorm:"column:package_url" json:"package_url"`    // Package Download URL
	CreatedAt      time.Time  `gorm:"column:created_at;not null" json:"created_at"`    // Creation Time
	UpdatedAt      *time.Time `gorm:"column:updated_at" json:"updated_at"`         // Last Updated Time
	Remark         *string    `gorm:"column:remark" json:"remark"`                           // Remarks
	Signature      *string    `gorm:"column:signature" json:"signature"`  // Upgrade Package Signature
	TenantID       *string    `gorm:"column:tenant_id" json:"tenant_id"`                                    // Tenant ID
}

// TableName OtaUpgradePackage's table name
func (*OtaUpgradePackage) TableName() string {
	return TableNameOtaUpgradePackage
}
