// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`                // UUID
	Name           string    `gorm:"column:name;not null" json:"name"`        // Product name
	Description    *string   `gorm:"column:description" json:"description"`    // Description
	ProductType    *string   `gorm:"column:product_type" json:"product_type"` // Product type
	ProductKey     *string   `gorm:"column:product_key" json:"product_key"`    // Product key
	ProductModel   *string   `gorm:"column:product_model" json:"product_model"` // Product model (ID)
	ImageURL       *string   `gorm:"column:image_url" json:"image_url"`              // Image URL
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"` // Creation time
	Remark         *string   `gorm:"column:remark" json:"remark"`                                  // Remarks
	AdditionalInfo *string   `gorm:"column:additional_info" json:"additional_info"`                // Additional information
	TenantID       *string   `gorm:"column:tenant_id" json:"tenant_id"`          // Tenant ID
	DeviceConfigID *string   `gorm:"column:device_config_id" json:"device_config_id"`              // Device configuration ID
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
