// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProtocolPlugin = "protocol_plugins"

// ProtocolPlugin mapped from table <protocol_plugins>
// ProtocolPlugin represents a protocol plugin for device communication.
type ProtocolPlugin struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"` // ID
	Name           string    `gorm:"column:name;not null" json:"name"` // Plugin name
	DeviceType     int16     `gorm:"column:device_type;not null;default:1" json:"device_type"` // Device type (1 - Direct device, 2 - Gateway device, default is direct)
	ProtocolType   string    `gorm:"column:protocol_type;not null" json:"protocol_type"` // Protocol type
	AccessAddress  *string   `gorm:"column:access_address" json:"access_address"` // Access address
	HTTPAddress    *string   `gorm:"column:http_address" json:"http_address"` // HTTP service address
	SubTopicPrefix *string   `gorm:"column:sub_topic_prefix" json:"sub_topic_prefix"` // Subscription topic prefix
	Description    *string   `gorm:"column:description" json:"description"` // Description
	AdditionalInfo *string   `gorm:"column:additional_info" json:"additional_info"` // Additional information
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"` // Creation time
	UpdateAt       time.Time `gorm:"column:update_at;not null" json:"update_at"` // Last updated
	Remark         *string   `gorm:"column:remark" json:"remark"` // Remarks
}

// TableName ProtocolPlugin's table name
func (*ProtocolPlugin) TableName() string {
	return TableNameProtocolPlugin
}
