// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSceneAutomation = "scene_automations"

// SceneAutomation mapped from table <scene_automations>
// SceneAutomation defines a scene automation rule for triggering actions based on specific conditions.
type SceneAutomation struct {
	ID          string     `gorm:"column:id;primaryKey" json:"id"`                     // Scene automation ID
	Name        string     `gorm:"column:name;not null" json:"name"`                   // Automation name
	Description *string    `gorm:"column:description" json:"description"`              // Description
	Enabled     string     `gorm:"column:enabled;not null" json:"enabled"`             // Enable status: Y - Enabled, N - Disabled
	TenantID    string     `gorm:"column:tenant_id;not null" json:"tenant_id"`         // Tenant ID
	Creator     string     `gorm:"column:creator;not null" json:"creator"`             // Creator ID
	Updator     string     `gorm:"column:updator;not null" json:"updator"`             // Last updated by (user ID)
	CreatedAt   time.Time  `gorm:"column:created_at;not null" json:"created_at"`       // Creation timestamp
	UpdatedAt   *time.Time `gorm:"column:updated_at" json:"updated_at"`                // Last update timestamp
	Remark      *string    `gorm:"column:remark" json:"remark"`                        // Remarks
}

// TableName SceneAutomation's table name
func (*SceneAutomation) TableName() string {
	return TableNameSceneAutomation
}
