// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSceneLog = "scene_log"

// SceneLog mapped from table <scene_log>
// SceneLog represents the log of a scene execution, including details about the execution result.
type SceneLog struct {
	SceneID         string    `gorm:"column:scene_id;not null" json:"scene_id"`                        // Scene ID (associated with deletion)
	ExecutedAt      time.Time `gorm:"column:executed_at;not null" json:"executed_at"`                  // Execution timestamp
	Detail          string    `gorm:"column:detail;not null" json:"detail"`                             // Execution details: detailed process of the execution
	ExecutionResult string    `gorm:"column:execution_result;not null" json:"execution_result"`        // Execution result: S = Success, F = Failure; Success only if all tasks execute successfully
	TenantID        string    `gorm:"column:tenant_id;not null" json:"tenant_id"`                      // Tenant ID
	Remark          *string   `gorm:"column:remark" json:"remark"`                                      // Remarks
	ID              string    `gorm:"column:id;primaryKey" json:"id"`                                   // Log ID
}

// TableName SceneLog's table name
func (*SceneLog) TableName() string {
	return TableNameSceneLog
}
