// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSceneAutomationLog = "scene_automation_log"

// SceneAutomationLog mapped from table <scene_automation_log>
// SceneAutomationLog represents the execution log of a scene automation task.
type SceneAutomationLog struct {
	SceneAutomationID string    `gorm:"column:scene_automation_id;not null" json:"scene_automation_id"` // Scene automation ID (foreign key with cascading delete)
	ExecutedAt        time.Time `gorm:"column:executed_at;not null" json:"executed_at"`                  // Execution timestamp
	Detail            string    `gorm:"column:detail;not null" json:"detail"`                            // Execution detail (step-by-step explanation)
	ExecutionResult   string    `gorm:"column:execution_result;not null" json:"execution_result"`        // Execution result: S - Success, F - Failure (all actions must succeed)
	TenantID          string    `gorm:"column:tenant_id;not null" json:"tenant_id"`                      // Tenant ID
	Remark            *string   `gorm:"column:remark" json:"remark"`                                     // Remarks
}

// TableName SceneAutomationLog's table name
func (*SceneAutomationLog) TableName() string {
	return TableNameSceneAutomationLog
}
