// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysFunction = "sys_function"

// SysFunction mapped from table <sys_function>
type SysFunction struct {
	ID          string  `gorm:"column:id;primaryKey" json:"id"`                                        
	Name        string  `gorm:"column:name;not null" json:"name"`                                    
	EnableFlag  string  `gorm:"column:enable_flag;not null" json:"enable_flag"` 
	Description *string `gorm:"column:description" json:"description"`                              
	Remark      *string `gorm:"column:remark" json:"remark"`                                        
}

// TableName SysFunction's table name
func (*SysFunction) TableName() string {
	return TableNameSysFunction
}
