// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUIElement = "sys_ui_elements"

// SysUIElement mapped from table <sys_ui_elements>
type SysUIElement struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`                                      // 主键ID
	ParentID     string    `gorm:"column:parent_id;not null" json:"parent_id"`                         // 父元素id
	ElementCode  string    `gorm:"column:element_code;not null" json:"element_code"`                   // 元素标识符
	ElementType  int16     `gorm:"column:element_type;not null" json:"element_type"` // 元素类型1-菜单 2-目录 3-按钮 4-路由
	Order_       *int16    `gorm:"column:orders" json:"orders"`                                           // 排序
	Param1       *string   `gorm:"column:param1" json:"param1"`
	Param2       *string   `gorm:"column:param2" json:"param2"`
	Param3       *string   `gorm:"column:param3" json:"param3"`
	Authority    string    `gorm:"column:authority;not null" json:"authority"` // 权限(多选)1-系统管理员 2-租户 例如[1,2]
	Description  *string   `gorm:"column:description" json:"description"`                              // 描述
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:"created_at"`
	Remark       *string   `gorm:"column:remark" json:"remark"`
	Multilingual *string   `gorm:"column:multilingual" json:"multilingual"` // 多语言标识符
	RoutePath    *string   `gorm:"column:route_path" json:"route_path"`
}

// TableName SysUIElement's table name
func (*SysUIElement) TableName() string {
	return TableNameSysUIElement
}
