// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysDictLanguage = "sys_dict_language"

// SysDictLanguage mapped from table <sys_dict_language>
type SysDictLanguage struct {
	ID           string `gorm:"column:id;primaryKey" json:"id"`                     
	DictID       string `gorm:"column:dict_id;not null" json:"dict_id"`      
	LanguageCode string `gorm:"column:language_code;not null" json:"language_code"` 
	Translation  string `gorm:"column:translation;not null" json:"translation"`      
}

// TableName SysDictLanguage's table name
func (*SysDictLanguage) TableName() string {
	return TableNameSysDictLanguage
}
