// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUIElement = "sys_ui_elements"

// SysUIElement mapped from table <sys_ui_elements>
type SysUIElement struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`                   // ID
	ParentID     string    `gorm:"column:parent_id;not null" json:"parent_id"`       // Parent ID
	ElementCode  string    `gorm:"column:element_code;not null" json:"element_code"` // Element Code
	ElementType  int16     `gorm:"column:element_type;not null" json:"element_type"` // Element Type: 1 - Menu, 2 - Directory, 3 - Button, 4 - Route
	Order_       *int16    `gorm:"column:orders" json:"orders"`                      // Order
	Param1       *string   `gorm:"column:param1" json:"param1"`
	Param2       *string   `gorm:"column:param2" json:"param2"`
	Param3       *string   `gorm:"column:param3" json:"param3"`
	Authority    string    `gorm:"column:authority;not null" json:"authority"` // Authority: 1 - System Admin, 2 - Tenant Admin
	Description  *string   `gorm:"column:description" json:"description"`      // Description
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:"created_at"`
	Remark       *string   `gorm:"column:remark" json:"remark"`
	Multilingual *string   `gorm:"column:multilingual" json:"multilingual"` // Multilingual Identifier
	RoutePath    *string   `gorm:"column:route_path" json:"route_path"`
}

// TableName SysUIElement's table name
func (*SysUIElement) TableName() string {
	return TableNameSysUIElement
}
