// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTelemetrySetLog = "telemetry_set_logs"

// TelemetrySetLog mapped from table <telemetry_set_logs>
// TelemetrySetLog represents the log for telemetry set operations, including device ID, operation type, status, error message, and other relevant information.
type TelemetrySetLog struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`                           // Unique log ID (primary key)
	DeviceID      string    `gorm:"column:device_id;not null" json:"device_id"`               // Device ID (foreign key, cascades on delete)
	OperationType *string   `gorm:"column:operation_type" json:"operation_type"`             // Operation type: 1 - Manual operation, 2 - Automatic trigger
	Datum         *string   `gorm:"column:data" json:"data"`                                  // Data sent (optional)
	Status        *string   `gorm:"column:status" json:"status"`                              // Status: 1 - Sent successfully, 2 - Failed
	ErrorMessage  *string   `gorm:"column:error_message" json:"error_message"`                // Error message (optional)
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`             // Creation timestamp
	UserID        *string   `gorm:"column:user_id" json:"user_id"`                            // User ID who performed the operation (optional)
	Description   *string   `gorm:"column:description" json:"description"`                    // Description of the log (optional)
}

// TableName TelemetrySetLog's table name
func (*TelemetrySetLog) TableName() string {
	return TableNameTelemetrySetLog
}
