// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
// User represents a system user, including personal details, contact information, status, role, password, and other metadata.
type User struct {
	ID                  string     `gorm:"column:id;primaryKey" json:"id"`                               // Unique user ID (primary key)
	Name                *string    `gorm:"column:name" json:"name"`                                       // Name of the user (optional)
	PhoneNumber         string     `gorm:"column:phone_number;not null" json:"phone_number"`              // User's phone number (required)
	Email               string     `gorm:"column:email;not null" json:"email"`                            // User's email address (required)
	Status              *string    `gorm:"column:status" json:"status"`                                   // User status: F - Frozen, N - Normal (optional)
	Authority           *string    `gorm:"column:authority" json:"authority"`                             // User role: TENANT_ADMIN - Tenant Admin, TENANT_USER - Tenant User, SYS_ADMIN - System Admin (optional)
	Password            string     `gorm:"column:password;not null" json:"password"`                      // User's password (required)
	TenantID            *string    `gorm:"column:tenant_id" json:"tenant_id"`                             // Tenant ID associated with the user (optional)
	Remark              *string    `gorm:"column:remark" json:"remark"`                                   // Additional remarks about the user (optional)
	AdditionalInfo      *string    `gorm:"column:additional_info;default:{}" json:"additional_info"`      // Extra user-related information (optional, defaults to empty)
	CreatedAt           *time.Time `gorm:"column:created_at" json:"created_at"`                           // Timestamp when the user was created (optional)
	UpdatedAt           *time.Time `gorm:"column:updated_at" json:"updated_at"`                           // Timestamp when the user was last updated (optional)
	PasswordLastUpdated *time.Time `gorm:"column:password_last_updated" json:"password_last_updated"`     // Timestamp when the password was last updated (optional)
	LastVisitTime       *time.Time `gorm:"column:last_visit_time" json:"last_visit_time"`                 // Timestamp of the last visit (optional)
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
