// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVisPluginLocal = "vis_plugin_local"

// VisPluginLocal mapped from table <vis_plugin_local>
type VisPluginLocal struct {
	ID        string     `gorm:"column:id;primaryKey" json:"id"`
	TenantID  string     `gorm:"column:tenant_id;not null" json:"tenant_id"`      
	PluginURL string     `gorm:"column:plugin_url;not null" json:"plugin_url"` 
	CreateAt  *time.Time `gorm:"column:create_at" json:"create_at"`               
	Remark    *string    `gorm:"column:remark" json:"remark"`
}

// TableName VisPluginLocal's table name
func (*VisPluginLocal) TableName() string {
	return TableNameVisPluginLocal
}
