// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVisPlugin = "vis_plugin"

// VisPlugin mapped from table <vis_plugin>
type VisPlugin struct {
	ID                string  `gorm:"column:id;primaryKey" json:"id"`
	TenantID          string  `gorm:"column:tenant_id;not null" json:"tenant_id"`          
	PluginName        string  `gorm:"column:plugin_name;not null" json:"plugin_name"`   
	PluginDescription *string `gorm:"column:plugin_description" json:"plugin_description"` 
	CreateAt          *int64  `gorm:"column:create_at" json:"create_at"`
	Remark            *string `gorm:"column:remark" json:"remark"`
}

// TableName VisPlugin's table name
func (*VisPlugin) TableName() string {
	return TableNameVisPlugin
}
