// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVisFile = "vis_files"

// VisFile mapped from table <vis_files>
type VisFile struct {
	ID          string  `gorm:"column:id;primaryKey" json:"id"`
	VisPluginID string  `gorm:"column:vis_plugin_id;not null" json:"vis_plugin_id"` 
	FileName    *string `gorm:"column:file_name" json:"file_name"`                       
	FileURL     *string `gorm:"column:file_url" json:"file_url"`                      
	FileSize    *string `gorm:"column:file_size" json:"file_size"`                     
	CreateAt    *int64  `gorm:"column:create_at" json:"create_at"`
	Remark      *string `gorm:"column:remark" json:"remark"`
}

// TableName VisFile's table name
func (*VisFile) TableName() string {
	return TableNameVisFile
}
